import type { CommandName, RunMetadata } from "./run-metadata.js";
import type { FleetAuditReport, PairConflictReport, ShardPlan } from "../types.js";
import type { OverloadResult } from "../shard/analyzer.js";
import type { ScanData, ScanPairEntry } from "../commands/scan.js";

// ── Public API ─────────────────────────────────────────────────

export function generateHtml(
  command: CommandName,
  metadata: RunMetadata,
  commandData: unknown
): string {
  let body: string;

  switch (command) {
    case "audit":
      body = renderAuditBody(commandData as FleetAuditReport);
      break;
    case "lint":
      body = renderLintBody(commandData as LintData);
      break;
    case "scan":
      body = renderScanBody(commandData as ScanData);
      break;
  }

  return wrapPage(command, metadata, body);
}

// ── Data shapes for lint ──────────────────────────────────────

export interface LintRewriteIteration {
  /** Description text AFTER this iteration was applied */
  description: string;
  reasoning: string;
}

export interface LintRewriteSuggestion {
  skillName: string;
  /** Description before any rewrite was applied */
  originalDescription: string;
  /** Description after the final rewrite was applied */
  rewrittenDescription: string;
  /** Reasoning from the final iteration */
  reasoning: string;
  conflictsWith: string[];
  /**
   * Per-iteration evolution. Present when --fix ran multiple iterations.
   * history[0] = description after iteration 1
   * history[N-1] = description after iteration N (same as rewrittenDescription)
   */
  history?: LintRewriteIteration[];
}

export interface ShardFinding {
  skillName: string;
  descriptionLength: number;
  isOverloaded: boolean;
  reason: string;
  overloadResult: OverloadResult;
  plan?: ShardPlan;
}

export interface LintMergeRecommendation {
  skillA: string;
  skillB: string;
  mergedName: string;
  mergedDescription: string;
  reasoning: string;
  accuracy: number;
}

export interface LintData {
  failingReports: PairConflictReport[];
  passingCount: number;
  rewriteSuggestions: LintRewriteSuggestion[];
  /** true when --fix was used and rewrites were written to disk */
  appliedRewrites: boolean;
  mergeRecommendations?: LintMergeRecommendation[];
  shardFindings: ShardFinding[];
}

// ── Severity helpers ───────────────────────────────────────────

const SEVERITY_ORDER: Record<string, number> = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3 };

const SEVERITY_COLORS: Record<string, string> = {
  CRITICAL: "#dc2626",
  HIGH: "#f59e0b",
  MEDIUM: "#3b82f6",
  LOW: "#22c55e",
};

function severityBadge(level: string): string {
  const color = SEVERITY_COLORS[level] || "#6b7280";
  return `<span style="display:inline-block;padding:2px 8px;border-radius:4px;font-size:12px;font-weight:600;color:#fff;background:${color}">${esc(level)}</span>`;
}

// ── Shared page wrapper ────────────────────────────────────────

function wrapPage(command: CommandName, meta: RunMetadata, body: string): string {
  const title = `Homingo ${capitalize(command)} Report`;
  const date = meta.timestamp.slice(0, 10);
  const duration = (meta.durationMs / 1000).toFixed(1);
  const totalTokens = meta.tokens.total.toLocaleString();

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)} — ${date}</title>
<style>${CSS}</style>
</head>
<body>
<header>
  <div class="header-row">
    <h1>🐦 ${esc(title)}</h1>
    <a href="../logs-viewer.html" class="home-link">← All Runs</a>
  </div>
  <div class="meta-bar">
    <span class="meta-item"><strong>Date:</strong> ${esc(date)}</span>
    <span class="meta-item"><strong>Model:</strong> ${esc(meta.model)}</span>
    ${meta.simModel && meta.simModel !== meta.model ? `<span class="meta-item"><strong>Sim:</strong> ${esc(meta.simModel)}</span>` : ""}
    <span class="meta-item"><strong>Provider:</strong> ${esc(meta.provider)}</span>
    <span class="meta-item"><strong>Skills:</strong> ${meta.skillCount}</span>
    <span class="meta-item"><strong>Duration:</strong> ${duration}s</span>
    <span class="meta-item"><strong>Tokens:</strong> ${totalTokens} (${meta.tokens.input.toLocaleString()} in / ${meta.tokens.output.toLocaleString()} out)</span>
    ${meta.cacheHits && meta.cacheHits > 0 ? `<span class="meta-item"><strong>Cached:</strong> ${meta.cacheHits} pair${meta.cacheHits !== 1 ? "s" : ""}</span>` : ""}
    ${meta.gitCommitHash ? `<span class="meta-item"><strong>Git:</strong> <code>${esc(meta.gitCommitHash)}</code></span>` : ""}
  </div>
</header>
${renderSkillInventory(meta)}
<main>
${body}
</main>
<footer>
  <p>Generated by <strong>Homingo</strong> · Run ID: <code>${esc(meta.id.slice(0, 8))}</code></p>
</footer>
</body>
</html>`;
}

// ── Skill inventory (collapsed) ────────────────────────────────

function renderSkillInventory(meta: RunMetadata): string {
  if (!meta.skills || meta.skills.length === 0) return "";

  let rows = "";
  for (const skill of meta.skills) {
    rows += `<tr>
      <td><strong>${esc(skill.name)}</strong></td>
      <td class="skill-desc">${esc(skill.description || "(no description)")}</td>
    </tr>`;
  }

  return `<details class="skill-inventory">
  <summary>Skills in this run (${meta.skills.length})</summary>
  <table>
    <thead><tr><th>Name</th><th>Description</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
</details>`;
}

// ── Audit renderer ─────────────────────────────────────────────

function renderAuditBody(report: FleetAuditReport): string {
  const sections = [
    { label: "CRITICAL", pairs: report.criticalPairs },
    { label: "HIGH", pairs: report.highPairs },
    { label: "MEDIUM", pairs: report.mediumPairs },
    { label: "LOW", pairs: report.lowPairs },
  ];

  let html = `
<div class="summary-cards">
  <div class="card card-stat">
    <div class="card-label">Fleet Error Rate</div>
    <div class="card-value">${report.estimatedFleetErrorRate}%</div>
  </div>
  <div class="card card-stat">
    <div class="card-label">Pairs Tested</div>
    <div class="card-value">${report.totalPairsTested}</div>
  </div>
  <div class="card card-stat">
    <div class="card-label">Total Skills</div>
    <div class="card-value">${report.totalSkills}</div>
  </div>
  <div class="card card-stat">
    <div class="card-label">Critical Pairs</div>
    <div class="card-value" style="color:${SEVERITY_COLORS.CRITICAL}">${report.criticalPairs.length}</div>
  </div>
</div>`;

  for (const section of sections) {
    if (section.pairs.length === 0) continue;
    html += renderPairSection(section.label, section.pairs);
  }

  if (report.topFiveOffenders.length > 0) {
    html += `<section><h2>Top Offenders</h2><ol>`;
    for (const name of report.topFiveOffenders) {
      html += `<li><strong>${esc(name)}</strong></li>`;
    }
    html += `</ol></section>`;
  }

  return html;
}

function renderPairSection(label: string, pairs: PairConflictReport[]): string {
  const color = SEVERITY_COLORS[label] || "#6b7280";

  let html = `<section>
  <h2 style="color:${color}">${esc(label)} <span class="count">(${pairs.length} pair${pairs.length !== 1 ? "s" : ""})</span></h2>
  <table>
    <thead><tr><th>Skill Pair</th><th>Accuracy</th><th>Action</th></tr></thead>
    <tbody>`;

  for (const pair of pairs) {
    html += `<tr>
      <td><strong>${esc(pair.skillA)}</strong> ↔ <strong>${esc(pair.skillB)}</strong></td>
      <td>${pair.routingAccuracy}%</td>
      <td>${esc(pair.recommendedAction)}</td>
    </tr>`;

    // Expandable misroute details
    if (pair.misroutes.length > 0) {
      html += `<tr><td colspan="3">
        <details>
          <summary>${pair.misroutes.length} misrouted prompt${pair.misroutes.length !== 1 ? "s" : ""}</summary>
          <ul class="misroute-list">`;
      for (const m of pair.misroutes.slice(0, 10)) {
        html += `<li>
          <span class="prompt-text">"${esc(m.promptText)}"</span>
          <br><span class="misroute-detail">Expected: <strong>${esc(m.expectedSkill)}</strong> → Got: <strong>${esc(m.selectedSkill)}</strong></span>
        </li>`;
      }
      if (pair.misroutes.length > 10) {
        html += `<li class="more">…and ${pair.misroutes.length - 10} more</li>`;
      }
      html += `</ul></details></td></tr>`;
    }
  }

  html += `</tbody></table></section>`;
  return html;
}

// ── Lint renderer ──────────────────────────────────────────────

function renderLintBody(data: LintData): string {
  const totalNeighbors = data.failingReports.length + data.passingCount;
  const allPassed = data.failingReports.length === 0;
  const overloaded = (data.shardFindings ?? []).filter((f) => f.isOverloaded);

  let html = `
<div class="summary-cards">
  <div class="card card-stat ${allPassed ? "card-pass" : "card-fail"}">
    <div class="card-label">Result</div>
    <div class="card-value">${allPassed ? "✅ PASS" : "❌ FAIL"}</div>
  </div>
  <div class="card card-stat">
    <div class="card-label">Pairs Tested</div>
    <div class="card-value">${totalNeighbors}</div>
  </div>
  <div class="card card-stat">
    <div class="card-label">Passing</div>
    <div class="card-value" style="color:${SEVERITY_COLORS.LOW}">${data.passingCount}</div>
  </div>
  <div class="card card-stat">
    <div class="card-label">Failing</div>
    <div class="card-value" style="color:${SEVERITY_COLORS.CRITICAL}">${data.failingReports.length}</div>
  </div>
</div>`;

  // Section nav
  const navLinks: Array<{ id: string; label: string }> = [];
  if (data.failingReports.length > 0)
    navLinks.push({ id: "failing-pairs", label: "Failing Pairs" });
  if (data.rewriteSuggestions.length > 0)
    navLinks.push({
      id: "rewrite-suggestions",
      label: data.appliedRewrites ? "Applied Rewrites" : "Rewrites",
    });
  const mergeRecs = data.mergeRecommendations ?? [];
  if (mergeRecs.length > 0)
    navLinks.push({ id: "merge-recommendations", label: "Merge Candidates" });
  if (overloaded.length > 0) navLinks.push({ id: "scope-overload", label: "Scope Overload" });
  navLinks.push({ id: "next-steps", label: "Next Steps" });

  if (navLinks.length > 1) {
    html += `<nav class="section-nav">${navLinks.map((l) => `<a href="#${l.id}">${esc(l.label)}</a>`).join("")}</nav>`;
  }

  if (data.failingReports.length > 0) {
    html += `<section id="failing-pairs"><h2>Failing Pairs</h2>`;
    html += `<table>
      <thead><tr><th>Skill Pair</th><th>Accuracy</th><th>Severity</th><th>Action</th></tr></thead>
      <tbody>`;
    for (const r of data.failingReports) {
      html += `<tr>
        <td>${esc(r.skillA)} ↔ ${esc(r.skillB)}</td>
        <td>${r.routingAccuracy}%</td>
        <td>${severityBadge(r.severityLevel)}</td>
        <td>${esc(r.recommendedAction)}</td>
      </tr>`;
    }
    html += `</tbody></table></section>`;
  }

  if (data.rewriteSuggestions.length > 0) {
    const sectionTitle = data.appliedRewrites ? "Applied Rewrites" : "Rewrite Suggestions";
    const afterLabel = data.appliedRewrites ? "Applied" : "Suggested";
    html += `<section id="rewrite-suggestions"><h2>${sectionTitle} <span class="count">(${data.rewriteSuggestions.length})</span></h2>`;
    for (const s of data.rewriteSuggestions) {
      const isMultiIteration = s.history && s.history.length > 1;
      html += `<div class="rewrite-card">
        <h3>${esc(s.skillName)}</h3>
        <p class="reasoning">${esc(s.reasoning)}</p>`;

      if (isMultiIteration) {
        // Timeline view: Original → Iter 1 → Iter 2 → ... → Final
        html += `<div class="rewrite-timeline">
          <div class="timeline-step timeline-original">
            <span class="timeline-label">Original</span>
            <pre>${esc(s.originalDescription)}</pre>
          </div>`;
        s.history!.forEach((iter, idx) => {
          const isLast = idx === s.history!.length - 1;
          html += `<div class="timeline-arrow">↓ Iteration ${idx + 1}${iter.reasoning ? ` — <em>${esc(iter.reasoning)}</em>` : ""}</div>
          <div class="timeline-step${isLast ? " timeline-final" : ""}">
            <span class="timeline-label">${isLast ? `✓ Final (${afterLabel})` : `Iteration ${idx + 1}`}</span>
            <pre>${esc(iter.description)}</pre>
          </div>`;
        });
        html += `</div>`;
      } else {
        // Simple before/after diff (single iteration or suggestion-only)
        html += `<div class="diff-view">
          <div class="diff-old"><strong>Before:</strong><pre>${esc(s.originalDescription)}</pre></div>
          <div class="diff-new"><strong>${esc(afterLabel)}:</strong><pre>${esc(s.rewrittenDescription)}</pre></div>
        </div>`;
      }

      html += `<p class="conflicts-with">Conflicts with: ${s.conflictsWith.map((c) => `<code>${esc(c)}</code>`).join(", ")}</p>
      </div>`;
    }
    html += `</section>`;
  }

  // Merge recommendations
  if (mergeRecs.length > 0) {
    html += `<section id="merge-recommendations">
      <h2>Merge Candidates <span class="count">(${mergeRecs.length})</span></h2>
      <p class="section-desc">These skill pairs appear to serve the same purpose. Consider merging them into a single skill.</p>`;

    for (const rec of mergeRecs) {
      html += `<div class="merge-card">
        <h3>${esc(rec.skillA)} + ${esc(rec.skillB)} → <code>${esc(rec.mergedName)}</code></h3>
        <p class="reasoning">${esc(rec.reasoning)}</p>
        <div class="merge-details">
          <p><strong>Current accuracy:</strong> ${rec.accuracy}%</p>
          <div class="diff-new">
            <strong>Suggested merged description:</strong>
            <pre>${esc(rec.mergedDescription)}</pre>
          </div>
        </div>
      </div>`;
    }

    html += `</section>`;
  }

  // Scope overload / shard findings
  if (overloaded.length > 0) {
    html += `<section id="scope-overload"><h2>Scope Overload</h2>
        <p class="section-desc">${overloaded.length} skill${overloaded.length !== 1 ? "s" : ""} detected as overloaded — descriptions cover too many intents.</p>`;

    for (const finding of overloaded) {
      html += `<div class="skill-card">
          <h3>${esc(finding.skillName)} <span class="count">(${finding.descriptionLength} chars)</span></h3>
          <p class="reasoning">${esc(finding.reason)}</p>`;

      if (finding.plan) {
        html += renderShardPlanDetails(finding.plan);
      }

      html += `</div>`;
    }

    html += `</section>`;
  }

  // Next Steps
  const hasIssues = data.failingReports.length > 0 || overloaded.length > 0 || mergeRecs.length > 0;
  if (hasIssues) {
    html += `<section id="next-steps" class="callout">
  <h2>Next Steps</h2>
  <ul>`;

    if (data.failingReports.length > 0) {
      html += `<li>Run <code>homingo lint --fix</code> to iteratively rewrite descriptions until pairs pass</li>`;
      html += `<li>Or skip re-testing and jump straight to fixing: <code>homingo lint --fix latest</code></li>`;

      // Specific --pair commands for failing pairs (capped at 5)
      if (data.failingReports.length > 1) {
        const topFailing = data.failingReports.slice(0, 5);
        html += `<li>Fix specific pairs:<ul>`;
        for (const r of topFailing) {
          html += `<li><code>homingo lint --pair ${esc(r.skillA)},${esc(r.skillB)} --fix</code></li>`;
        }
        html += `</ul></li>`;
      }
    }

    if (mergeRecs.length > 0) {
      html += `<li><strong>${mergeRecs.length} merge candidate${mergeRecs.length !== 1 ? "s" : ""}</strong> detected — these skills may serve the same purpose. Review the merge recommendations and consolidate manually.</li>`;
    }

    if (overloaded.length > 0) {
      html += `<li>Run <code>homingo lint --fix</code> to generate and apply shard plans for ${overloaded.length} overloaded skill${overloaded.length !== 1 ? "s" : ""}</li>`;
    }

    html += `<li>Review changes with <code>git diff</code> before committing — Homingo writes files but never commits</li>`;
    html += `</ul></section>`;
  } else {
    html += `<section id="next-steps" class="callout callout-success">
  <h2>All Clear</h2>
  <p>All pairs pass the accuracy threshold and no skills are overloaded. Safe to deploy.</p>
</section>`;
  }

  return html;
}

// ── Shard plan detail renderer (used within lint reports) ──────

function renderShardPlanDetails(plan: ShardPlan): string {
  let html = `
  <div class="shard-details">
    <p><strong>Identified Intents:</strong></p>
    <ol>`;
  for (const intent of plan.identifiedIntents) {
    html += `<li>${esc(intent)}</li>`;
  }
  html += `</ol>

    <p><strong>Proposed Sub-Skills:</strong></p>`;
  for (const sub of plan.subSkills) {
    html += `<div class="skill-card">
      <h3>${esc(sub.name)}</h3>
      <p>${esc(sub.description)}</p>
      <p><strong>Intents:</strong> ${sub.intents.map((i) => `<code>${esc(i)}</code>`).join(", ")}</p>
      ${sub.negativeTriggers.length > 0 ? `<p class="negative-triggers"><strong>Negative triggers:</strong> ${sub.negativeTriggers.map((t) => `<em>${esc(t)}</em>`).join(" · ")}</p>` : ""}
    </div>`;
  }

  html += `<p><strong>Orchestrator:</strong></p>
    <div class="skill-card orchestrator-card">
      <h3>${esc(plan.orchestrator.name)}</h3>
      <p>${esc(plan.orchestrator.description)}</p>
      ${plan.orchestrator.negativeTriggers.length > 0 ? `<p class="negative-triggers"><strong>Negative triggers:</strong> ${plan.orchestrator.negativeTriggers.map((t) => `<em>${esc(t)}</em>`).join(" · ")}</p>` : ""}
    </div>
  </div>`;

  return html;
}

// ── Scan renderer ───────────────────────────────────────────────

function renderScanBody(data: ScanData): string {
  const scoreColor =
    data.healthScore >= 80
      ? SEVERITY_COLORS.LOW
      : data.healthScore >= 50
        ? SEVERITY_COLORS.HIGH
        : SEVERITY_COLORS.CRITICAL;

  const overlapFindings = data.overlapPairs
    .filter((p: ScanPairEntry) => p.severity !== "LOW")
    .sort((a, b) => {
      const tierDiff = (SEVERITY_ORDER[a.severity] ?? 3) - (SEVERITY_ORDER[b.severity] ?? 3);
      if (tierDiff !== 0) return tierDiff;
      return b.overlapScore - a.overlapScore;
    });

  let html = `
<div class="summary-cards">
  <div class="card card-stat">
    <div class="card-label">Health Score</div>
    <div class="card-value" style="color:${scoreColor}">${data.healthScore}/100</div>
  </div>
  <div class="card card-stat">
    <div class="card-label">Total Skills</div>
    <div class="card-value">${data.totalSkills}</div>
  </div>
  <div class="card card-stat">
    <div class="card-label">Overlap Findings</div>
    <div class="card-value" style="color:${overlapFindings.length > 0 ? SEVERITY_COLORS.CRITICAL : SEVERITY_COLORS.LOW}">${overlapFindings.length}</div>
  </div>
  <div class="card card-stat">
    <div class="card-label">Overloaded Skills</div>
    <div class="card-value" style="color:${data.overloadFindings.length > 0 ? SEVERITY_COLORS.HIGH : SEVERITY_COLORS.LOW}">${data.overloadFindings.length}</div>
  </div>
  <div class="card card-stat">
    <div class="card-label">Duplicate Skills</div>
    <div class="card-value" style="color:${data.duplicateFindings.length > 0 ? SEVERITY_COLORS.CRITICAL : SEVERITY_COLORS.LOW}">${data.duplicateFindings.length}</div>
  </div>
</div>`;

  // Section nav — only include links for sections that exist
  const navLinks: Array<{ id: string; label: string }> = [];
  if (overlapFindings.length > 0) {
    navLinks.push({ id: "overlap-findings", label: "Overlap Findings" });
    navLinks.push({ id: "conflicts-by-skill", label: "By Skill" });
  }
  if (data.overloadFindings.length > 0)
    navLinks.push({ id: "scope-overload", label: "Scope Overload" });
  if (data.duplicateFindings.length > 0)
    navLinks.push({ id: "duplicate-skills", label: "Duplicates" });
  navLinks.push({ id: "next-steps", label: "Next Steps" });

  if (navLinks.length > 1) {
    html += `<nav class="section-nav">${navLinks.map((l) => `<a href="#${l.id}">${esc(l.label)}</a>`).join("")}</nav>`;
  }

  if (overlapFindings.length > 0) {
    html += `<section id="overlap-findings">
  <h2>Overlap Findings <span class="count">(${overlapFindings.length})</span></h2>
  <table>
    <thead><tr><th>Skill Pair</th><th>Overlap</th><th>Severity</th><th>Reason</th></tr></thead>
    <tbody>`;
    for (const pair of overlapFindings) {
      html += `<tr>
      <td><strong>${esc(pair.skillA)}</strong> ↔ <strong>${esc(pair.skillB)}</strong></td>
      <td>${(pair.overlapScore * 100).toFixed(0)}%</td>
      <td>${severityBadge(pair.severity)}</td>
      <td>${esc(pair.reason)}</td>
    </tr>`;
    }
    html += `</tbody></table></section>`;

    // Conflicts by Skill — aggregate per-skill view
    const skillConflicts = new Map<
      string,
      {
        conflicts: Array<{ partner: string; severity: string; overlapScore: number }>;
        worstSeverity: string;
      }
    >();

    for (const pair of overlapFindings) {
      for (const [self, partner] of [
        [pair.skillA, pair.skillB],
        [pair.skillB, pair.skillA],
      ] as [string, string][]) {
        let entry = skillConflicts.get(self);
        if (!entry) {
          entry = { conflicts: [], worstSeverity: "LOW" };
          skillConflicts.set(self, entry);
        }
        entry.conflicts.push({
          partner,
          severity: pair.severity,
          overlapScore: pair.overlapScore,
        });
        if ((SEVERITY_ORDER[pair.severity] ?? 3) < (SEVERITY_ORDER[entry.worstSeverity] ?? 3)) {
          entry.worstSeverity = pair.severity;
        }
      }
    }

    const sortedSkills = [...skillConflicts.entries()].sort((a, b) => {
      const sevDiff =
        (SEVERITY_ORDER[a[1].worstSeverity] ?? 3) - (SEVERITY_ORDER[b[1].worstSeverity] ?? 3);
      if (sevDiff !== 0) return sevDiff;
      return b[1].conflicts.length - a[1].conflicts.length;
    });

    html += `<section id="conflicts-by-skill">
  <h2>Conflicts by Skill <span class="count">(${sortedSkills.length} skill${sortedSkills.length !== 1 ? "s" : ""})</span></h2>
  <details open>
    <summary>Skills involved in overlap findings (${sortedSkills.length})</summary>`;

    for (const [skillName, info] of sortedSkills) {
      const sortedConflicts = [...info.conflicts].sort((a, b) => {
        const sevDiff = (SEVERITY_ORDER[a.severity] ?? 3) - (SEVERITY_ORDER[b.severity] ?? 3);
        if (sevDiff !== 0) return sevDiff;
        return b.overlapScore - a.overlapScore;
      });

      html += `<div class="skill-card">
      <h3>${esc(skillName)} ${severityBadge(info.worstSeverity)} <span class="count">${info.conflicts.length} conflict${info.conflicts.length !== 1 ? "s" : ""}</span></h3>
      <table>
        <thead><tr><th>Conflicting Skill</th><th>Overlap</th><th>Severity</th></tr></thead>
        <tbody>`;

      for (const c of sortedConflicts) {
        html += `<tr>
        <td>${esc(c.partner)}</td>
        <td>${(c.overlapScore * 100).toFixed(0)}%</td>
        <td>${severityBadge(c.severity)}</td>
      </tr>`;
      }

      html += `</tbody></table></div>`;
    }

    html += `</details></section>`;
  }

  if (data.overloadFindings.length > 0) {
    html += `<section id="scope-overload">
  <h2 style="color:${SEVERITY_COLORS.HIGH}">Scope Overload <span class="count">(${data.overloadFindings.length} skill${data.overloadFindings.length !== 1 ? "s" : ""})</span></h2>
  <p class="section-desc">These skills have descriptions that cover too many intents, which may cause routing confusion.</p>
  <table>
    <thead><tr><th>Skill</th><th>Length</th><th>Reason</th></tr></thead>
    <tbody>`;
    for (const finding of data.overloadFindings) {
      html += `<tr>
      <td><strong>${esc(finding.skillName)}</strong></td>
      <td>${finding.descriptionLength} chars</td>
      <td>${esc(finding.reason)}</td>
    </tr>`;
    }
    html += `</tbody></table></section>`;
  }

  if (data.duplicateFindings.length > 0) {
    html += `<section id="duplicate-skills">
  <h2 style="color:${SEVERITY_COLORS.CRITICAL}">Duplicate Skills <span class="count">(${data.duplicateFindings.length})</span></h2>
  <p class="section-desc">Multiple SKILL.md files resolve to the same name. Only the first occurrence is used — duplicates are skipped.</p>
  <table>
    <thead><tr><th>Skill Name</th><th>Kept</th><th>Skipped</th></tr></thead>
    <tbody>`;
    for (const dup of data.duplicateFindings) {
      html += `<tr>
      <td><strong>${esc(dup.name)}</strong></td>
      <td>${esc(dup.keptPath)}</td>
      <td>${esc(dup.skippedPath)}</td>
    </tr>`;
    }
    html += `</tbody></table></section>`;
  }

  // Next steps callout
  const hasIssues =
    overlapFindings.length > 0 ||
    data.overloadFindings.length > 0 ||
    data.duplicateFindings.length > 0;
  if (hasIssues) {
    html += `<section id="next-steps" class="callout">
  <h2>Next Steps</h2>
  <ul>`;
    if (overlapFindings.length > 0) {
      html += `<li>Run <code>homingo audit</code> to measure actual routing accuracy for overlap findings</li>`;

      // Add specific --pair lint commands for CRITICAL and HIGH findings (capped at 5)
      const actionablePairs = overlapFindings
        .filter((p: ScanPairEntry) => p.severity === "CRITICAL" || p.severity === "HIGH")
        .slice(0, 5);
      if (actionablePairs.length > 0) {
        html += `<li>Lint specific pairs:<ul>`;
        for (const pair of actionablePairs) {
          html += `<li><code>homingo lint --pair ${esc(pair.skillA)},${esc(pair.skillB)}</code></li>`;
        }
        html += `</ul></li>`;
      }
    }
    if (data.overloadFindings.length > 0) {
      html += `<li>Run <code>homingo lint --fix</code> to get rewrite suggestions and shard plans for overloaded skills</li>`;
    }
    if (data.duplicateFindings.length > 0) {
      html += `<li>Rename or remove duplicate skills to avoid routing ambiguity</li>`;
    }
    html += `</ul></section>`;
  } else {
    html += `<section id="next-steps" class="callout callout-success">
  <h2>Fleet Looks Healthy</h2>
  <p>No critical overlaps or overloaded skills detected. Run <code>homingo audit</code> for a full routing accuracy test.</p>
</section>`;
  }

  return html;
}

// ── Utilities ──────────────────────────────────────────────────

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// ── CSS ────────────────────────────────────────────────────────

const CSS = `
:root {
  --bg: #f8fafc;
  --card-bg: #ffffff;
  --text: #1e293b;
  --text-muted: #64748b;
  --border: #e2e8f0;
  --critical: #dc2626;
  --high: #f59e0b;
  --medium: #3b82f6;
  --low: #22c55e;
  --accent: #6366f1;
}

* { margin: 0; padding: 0; box-sizing: border-box; }

body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
  padding: 2rem;
  max-width: 1200px;
  margin: 0 auto;
}

header {
  margin-bottom: 2rem;
  padding-bottom: 1rem;
  border-bottom: 2px solid var(--border);
}

header h1 {
  font-size: 1.5rem;
  margin-bottom: 0;
}

.header-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 0.75rem;
}

.home-link {
  color: var(--accent);
  text-decoration: none;
  font-size: 0.9rem;
  font-weight: 500;
  padding: 0.4rem 0.75rem;
  border: 1px solid var(--accent);
  border-radius: 6px;
  transition: background 0.15s, color 0.15s;
}

.home-link:hover {
  background: var(--accent);
  color: #fff;
}

.meta-bar {
  display: flex;
  flex-wrap: wrap;
  gap: 1rem;
  font-size: 0.85rem;
  color: var(--text-muted);
}

.meta-item code {
  font-family: "SF Mono", "Fira Code", monospace;
  background: var(--border);
  padding: 1px 4px;
  border-radius: 3px;
  font-size: 0.8rem;
}

.section-nav {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  margin-bottom: 1.5rem;
  padding: 0.75rem 1rem;
  background: var(--card-bg);
  border: 1px solid var(--border);
  border-radius: 8px;
  position: sticky;
  top: 0;
  z-index: 10;
}
.section-nav a {
  color: var(--accent);
  text-decoration: none;
  font-size: 0.85rem;
  font-weight: 500;
  padding: 0.25rem 0.75rem;
  border-radius: 4px;
  transition: background 0.15s;
}
.section-nav a:hover {
  background: #e0e7ff;
  text-decoration: none;
}

.summary-cards {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  gap: 1rem;
  margin-bottom: 2rem;
}

.card {
  background: var(--card-bg);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1rem 1.25rem;
}

.card-stat .card-label {
  font-size: 0.8rem;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.card-stat .card-value {
  font-size: 1.75rem;
  font-weight: 700;
  margin-top: 0.25rem;
}

.card-pass { border-left: 4px solid var(--low); }
.card-fail { border-left: 4px solid var(--critical); }

section {
  margin-bottom: 2rem;
  scroll-margin-top: 3.5rem;
}

section h2 {
  font-size: 1.25rem;
  margin-bottom: 0.75rem;
}

.count {
  font-weight: 400;
  font-size: 0.9rem;
  color: var(--text-muted);
}

table {
  width: 100%;
  border-collapse: collapse;
  background: var(--card-bg);
  border-radius: 8px;
  overflow: hidden;
  border: 1px solid var(--border);
}

thead th {
  text-align: left;
  padding: 0.75rem 1rem;
  background: #f1f5f9;
  font-size: 0.8rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--text-muted);
}

tbody td {
  padding: 0.75rem 1rem;
  border-top: 1px solid var(--border);
  font-size: 0.9rem;
}

details {
  margin: 0.5rem 0;
}

summary {
  cursor: pointer;
  font-size: 0.85rem;
  color: var(--accent);
  font-weight: 500;
}

.misroute-list {
  list-style: none;
  padding: 0.5rem 0;
}

.misroute-list li {
  padding: 0.5rem 0;
  border-bottom: 1px solid var(--border);
  font-size: 0.85rem;
}

.misroute-list li:last-child { border-bottom: none; }

.prompt-text {
  font-style: italic;
  color: var(--text-muted);
}

.misroute-detail {
  font-size: 0.8rem;
}

.more {
  color: var(--text-muted);
  font-style: italic;
}

.rewrite-card {
  background: var(--card-bg);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1.25rem;
  margin-bottom: 1rem;
}

.rewrite-card h3 { margin-bottom: 0.5rem; }
.rewrite-card .reasoning { color: var(--text-muted); font-size: 0.9rem; margin-bottom: 0.75rem; }

.rewrite-timeline { display: flex; flex-direction: column; gap: 0; }
.timeline-step { border: 1px solid var(--border); border-radius: 6px; padding: 0.75rem 1rem; background: var(--bg); }
.timeline-step.timeline-original { border-left: 3px solid var(--text-muted); }
.timeline-step.timeline-final { border-left: 3px solid #22c55e; }
.timeline-label { display: inline-block; font-size: 0.75rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; color: var(--text-muted); margin-bottom: 0.4rem; }
.timeline-step.timeline-final .timeline-label { color: #22c55e; }
.timeline-step pre { margin: 0; white-space: pre-wrap; word-break: break-word; font-size: 0.85rem; }
.timeline-arrow { padding: 0.35rem 1rem; font-size: 0.8rem; color: var(--text-muted); font-style: italic; }
.timeline-arrow em { font-style: normal; }

.merge-card {
  background: var(--card-bg);
  border: 1px solid #a5b4fc;
  border-left: 4px solid var(--accent);
  border-radius: 8px;
  padding: 1.25rem;
  margin-bottom: 1rem;
}

.merge-card h3 { margin-bottom: 0.5rem; }
.merge-card .reasoning { color: var(--text-muted); font-size: 0.9rem; margin-bottom: 0.75rem; }
.merge-details { margin-top: 0.75rem; }

.diff-view {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1rem;
  margin-bottom: 0.75rem;
}

.diff-old, .diff-new {
  border-radius: 6px;
  padding: 0.75rem;
  font-size: 0.85rem;
}

.diff-old {
  background: #fef2f2;
  border: 1px solid #fecaca;
}

.diff-new {
  background: #f0fdf4;
  border: 1px solid #bbf7d0;
}

.diff-old pre, .diff-new pre {
  white-space: pre-wrap;
  word-break: break-word;
  font-family: "SF Mono", "Fira Code", monospace;
  font-size: 0.8rem;
  margin-top: 0.5rem;
}

.conflicts-with { font-size: 0.85rem; color: var(--text-muted); }
.conflicts-with code { background: var(--border); padding: 1px 4px; border-radius: 3px; }

.skill-card {
  background: var(--card-bg);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1.25rem;
  margin-bottom: 1rem;
}

.skill-card h3 { margin-bottom: 0.5rem; }
.skill-card code { background: var(--border); padding: 1px 4px; border-radius: 3px; font-size: 0.8rem; }

.orchestrator-card {
  border-left: 4px solid var(--accent);
}

.negative-triggers {
  font-size: 0.85rem;
  color: var(--text-muted);
  margin-top: 0.5rem;
}

.negative-triggers em {
  background: #fef3c7;
  padding: 1px 4px;
  border-radius: 3px;
  font-style: normal;
  font-size: 0.8rem;
}

.section-desc {
  color: var(--text-muted);
  font-size: 0.9rem;
  margin-bottom: 1rem;
}

.shard-details {
  margin-top: 1rem;
  padding-top: 0.75rem;
  border-top: 1px solid var(--border);
}

footer {
  margin-top: 3rem;
  padding-top: 1rem;
  border-top: 1px solid var(--border);
  text-align: center;
  font-size: 0.8rem;
  color: var(--text-muted);
}

footer code {
  font-family: "SF Mono", "Fira Code", monospace;
  background: var(--border);
  padding: 1px 4px;
  border-radius: 3px;
}

ol, ul { padding-left: 1.5rem; }
li { margin-bottom: 0.25rem; }

.callout {
  background: #fefce8;
  border: 1px solid #fde68a;
  border-radius: 8px;
  padding: 1.25rem;
}

.callout h2 { font-size: 1.1rem; margin-bottom: 0.5rem; }
.callout code {
  font-family: "SF Mono", "Fira Code", monospace;
  background: #fef3c7;
  padding: 1px 4px;
  border-radius: 3px;
  font-size: 0.85rem;
}

.callout-success {
  background: #f0fdf4;
  border-color: #bbf7d0;
}

.callout-success code {
  background: #dcfce7;
}

.skill-inventory {
  margin-bottom: 2rem;
  background: var(--card-bg);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 0.75rem 1rem;
}

.skill-inventory summary {
  cursor: pointer;
  font-size: 0.9rem;
  font-weight: 500;
  color: var(--text-muted);
}

.skill-inventory table { margin-top: 0.75rem; }

.skill-desc {
  font-size: 0.85rem;
  color: var(--text-muted);
  max-width: 600px;
}

@media (max-width: 768px) {
  body { padding: 1rem; }
  .summary-cards { grid-template-columns: 1fr 1fr; }
  .diff-view { grid-template-columns: 1fr; }
  .meta-bar { flex-direction: column; gap: 0.5rem; }
}
`;
