import type { CommandName, RunMetadata } from "./run-metadata.js";
import type { FleetAuditReport, PairConflictReport, ShardPlan } from "../types.js";
import type { OverloadResult } from "../shard/analyzer.js";
import type { ScanData, ScanPairEntry } from "../commands/scan.js";

// ── Public API ─────────────────────────────────────────────────

export function generateHtml(
  command: CommandName,
  metadata: RunMetadata,
  commandData: unknown
): string {
  let body: string;

  switch (command) {
    case "audit":
      body = renderAuditBody(commandData as FleetAuditReport);
      break;
    case "lint":
      body = renderLintBody(commandData as LintData);
      break;
    case "scan":
      body = renderScanBody(commandData as ScanData);
      break;
  }

  return wrapPage(command, metadata, body);
}

// ── Data shapes for lint ──────────────────────────────────────

export interface LintRewriteSuggestion {
  skillName: string;
  originalDescription: string;
  rewrittenDescription: string;
  reasoning: string;
  conflictsWith: string[];
}

export interface ShardFinding {
  skillName: string;
  descriptionLength: number;
  isOverloaded: boolean;
  reason: string;
  overloadResult: OverloadResult;
  plan?: ShardPlan;
}

export interface LintData {
  failingReports: PairConflictReport[];
  passingCount: number;
  rewriteSuggestions: LintRewriteSuggestion[];
  shardFindings: ShardFinding[];
}

// ── Severity helpers ───────────────────────────────────────────

const SEVERITY_COLORS: Record<string, string> = {
  CRITICAL: "#dc2626",
  HIGH: "#f59e0b",
  MEDIUM: "#3b82f6",
  LOW: "#22c55e",
};

function severityBadge(level: string): string {
  const color = SEVERITY_COLORS[level] || "#6b7280";
  return `<span style="display:inline-block;padding:2px 8px;border-radius:4px;font-size:12px;font-weight:600;color:#fff;background:${color}">${esc(level)}</span>`;
}

// ── Shared page wrapper ────────────────────────────────────────

function wrapPage(command: CommandName, meta: RunMetadata, body: string): string {
  const title = `Homingo ${capitalize(command)} Report`;
  const date = meta.timestamp.slice(0, 10);
  const duration = (meta.durationMs / 1000).toFixed(1);
  const totalTokens = meta.tokens.total.toLocaleString();

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)} — ${date}</title>
<style>${CSS}</style>
</head>
<body>
<header>
  <div class="header-row">
    <h1>🐦 ${esc(title)}</h1>
    <a href="../logs-viewer.html" class="home-link">← All Runs</a>
  </div>
  <div class="meta-bar">
    <span class="meta-item"><strong>Date:</strong> ${esc(date)}</span>
    <span class="meta-item"><strong>Model:</strong> ${esc(meta.model)}</span>
    <span class="meta-item"><strong>Provider:</strong> ${esc(meta.provider)}</span>
    <span class="meta-item"><strong>Skills:</strong> ${meta.skillCount}</span>
    <span class="meta-item"><strong>Duration:</strong> ${duration}s</span>
    <span class="meta-item"><strong>Tokens:</strong> ${totalTokens} (${meta.tokens.input.toLocaleString()} in / ${meta.tokens.output.toLocaleString()} out)</span>
    ${meta.gitCommitHash ? `<span class="meta-item"><strong>Git:</strong> <code>${esc(meta.gitCommitHash)}</code></span>` : ""}
  </div>
</header>
${renderSkillInventory(meta)}
<main>
${body}
</main>
<footer>
  <p>Generated by <strong>Homingo</strong> · Run ID: <code>${esc(meta.id.slice(0, 8))}</code></p>
</footer>
</body>
</html>`;
}

// ── Skill inventory (collapsed) ────────────────────────────────

function renderSkillInventory(meta: RunMetadata): string {
  if (!meta.skills || meta.skills.length === 0) return "";

  let rows = "";
  for (const skill of meta.skills) {
    rows += `<tr>
      <td><strong>${esc(skill.name)}</strong></td>
      <td class="skill-desc">${esc(skill.description || "(no description)")}</td>
    </tr>`;
  }

  return `<details class="skill-inventory">
  <summary>Skills in this run (${meta.skills.length})</summary>
  <table>
    <thead><tr><th>Name</th><th>Description</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
</details>`;
}

// ── Audit renderer ─────────────────────────────────────────────

function renderAuditBody(report: FleetAuditReport): string {
  const sections = [
    { label: "CRITICAL", pairs: report.criticalPairs },
    { label: "HIGH", pairs: report.highPairs },
    { label: "MEDIUM", pairs: report.mediumPairs },
    { label: "LOW", pairs: report.lowPairs },
  ];

  let html = `
<div class="summary-cards">
  <div class="card card-stat">
    <div class="card-label">Fleet Error Rate</div>
    <div class="card-value">${report.estimatedFleetErrorRate}%</div>
  </div>
  <div class="card card-stat">
    <div class="card-label">Pairs Tested</div>
    <div class="card-value">${report.totalPairsTested}</div>
  </div>
  <div class="card card-stat">
    <div class="card-label">Total Skills</div>
    <div class="card-value">${report.totalSkills}</div>
  </div>
  <div class="card card-stat">
    <div class="card-label">Critical Pairs</div>
    <div class="card-value" style="color:${SEVERITY_COLORS.CRITICAL}">${report.criticalPairs.length}</div>
  </div>
</div>`;

  for (const section of sections) {
    if (section.pairs.length === 0) continue;
    html += renderPairSection(section.label, section.pairs);
  }

  if (report.topFiveOffenders.length > 0) {
    html += `<section><h2>Top Offenders</h2><ol>`;
    for (const name of report.topFiveOffenders) {
      html += `<li><strong>${esc(name)}</strong></li>`;
    }
    html += `</ol></section>`;
  }

  return html;
}

function renderPairSection(label: string, pairs: PairConflictReport[]): string {
  const color = SEVERITY_COLORS[label] || "#6b7280";

  let html = `<section>
  <h2 style="color:${color}">${esc(label)} <span class="count">(${pairs.length} pair${pairs.length !== 1 ? "s" : ""})</span></h2>
  <table>
    <thead><tr><th>Skill Pair</th><th>Accuracy</th><th>Action</th></tr></thead>
    <tbody>`;

  for (const pair of pairs) {
    html += `<tr>
      <td><strong>${esc(pair.skillA)}</strong> ↔ <strong>${esc(pair.skillB)}</strong></td>
      <td>${pair.routingAccuracy}%</td>
      <td>${esc(pair.recommendedAction)}</td>
    </tr>`;

    // Expandable misroute details
    if (pair.misroutes.length > 0) {
      html += `<tr><td colspan="3">
        <details>
          <summary>${pair.misroutes.length} misrouted prompt${pair.misroutes.length !== 1 ? "s" : ""}</summary>
          <ul class="misroute-list">`;
      for (const m of pair.misroutes.slice(0, 10)) {
        html += `<li>
          <span class="prompt-text">"${esc(m.promptText)}"</span>
          <br><span class="misroute-detail">Expected: <strong>${esc(m.expectedSkill)}</strong> → Got: <strong>${esc(m.selectedSkill)}</strong></span>
        </li>`;
      }
      if (pair.misroutes.length > 10) {
        html += `<li class="more">…and ${pair.misroutes.length - 10} more</li>`;
      }
      html += `</ul></details></td></tr>`;
    }
  }

  html += `</tbody></table></section>`;
  return html;
}

// ── Lint renderer ──────────────────────────────────────────────

function renderLintBody(data: LintData): string {
  const totalNeighbors = data.failingReports.length + data.passingCount;
  const allPassed = data.failingReports.length === 0;

  let html = `
<div class="summary-cards">
  <div class="card card-stat ${allPassed ? "card-pass" : "card-fail"}">
    <div class="card-label">Result</div>
    <div class="card-value">${allPassed ? "✅ PASS" : "❌ FAIL"}</div>
  </div>
  <div class="card card-stat">
    <div class="card-label">Neighbors Tested</div>
    <div class="card-value">${totalNeighbors}</div>
  </div>
  <div class="card card-stat">
    <div class="card-label">Passing</div>
    <div class="card-value" style="color:${SEVERITY_COLORS.LOW}">${data.passingCount}</div>
  </div>
  <div class="card card-stat">
    <div class="card-label">Failing</div>
    <div class="card-value" style="color:${SEVERITY_COLORS.CRITICAL}">${data.failingReports.length}</div>
  </div>
</div>`;

  if (data.failingReports.length > 0) {
    html += `<section><h2>Failing Pairs</h2>`;
    html += `<table>
      <thead><tr><th>Skill Pair</th><th>Accuracy</th><th>Severity</th><th>Action</th></tr></thead>
      <tbody>`;
    for (const r of data.failingReports) {
      html += `<tr>
        <td>${esc(r.skillA)} ↔ ${esc(r.skillB)}</td>
        <td>${r.routingAccuracy}%</td>
        <td>${severityBadge(r.severityLevel)}</td>
        <td>${esc(r.recommendedAction)}</td>
      </tr>`;
    }
    html += `</tbody></table></section>`;
  }

  if (data.rewriteSuggestions.length > 0) {
    html += `<section><h2>Rewrite Suggestions</h2>`;
    for (const s of data.rewriteSuggestions) {
      html += `<div class="rewrite-card">
        <h3>${esc(s.skillName)}</h3>
        <p class="reasoning">${esc(s.reasoning)}</p>
        <div class="diff-view">
          <div class="diff-old"><strong>Original:</strong><pre>${esc(s.originalDescription)}</pre></div>
          <div class="diff-new"><strong>Suggested:</strong><pre>${esc(s.rewrittenDescription)}</pre></div>
        </div>
        <p class="conflicts-with">Conflicts with: ${s.conflictsWith.map((c) => `<code>${esc(c)}</code>`).join(", ")}</p>
      </div>`;
    }
    html += `</section>`;
  }

  // Scope overload / shard findings
  if (data.shardFindings && data.shardFindings.length > 0) {
    const overloaded = data.shardFindings.filter((f) => f.isOverloaded);

    if (overloaded.length > 0) {
      html += `<section><h2>Scope Overload</h2>
        <p class="section-desc">${overloaded.length} skill${overloaded.length !== 1 ? "s" : ""} detected as overloaded — descriptions cover too many intents.</p>`;

      for (const finding of overloaded) {
        html += `<div class="skill-card">
          <h3>${esc(finding.skillName)} <span class="count">(${finding.descriptionLength} chars)</span></h3>
          <p class="reasoning">${esc(finding.reason)}</p>`;

        if (finding.plan) {
          html += renderShardPlanDetails(finding.plan);
        }

        html += `</div>`;
      }

      html += `</section>`;
    }
  }

  return html;
}

// ── Shard plan detail renderer (used within lint reports) ──────

function renderShardPlanDetails(plan: ShardPlan): string {
  let html = `
  <div class="shard-details">
    <p><strong>Identified Intents:</strong></p>
    <ol>`;
  for (const intent of plan.identifiedIntents) {
    html += `<li>${esc(intent)}</li>`;
  }
  html += `</ol>

    <p><strong>Proposed Sub-Skills:</strong></p>`;
  for (const sub of plan.subSkills) {
    html += `<div class="skill-card">
      <h3>${esc(sub.name)}</h3>
      <p>${esc(sub.description)}</p>
      <p><strong>Intents:</strong> ${sub.intents.map((i) => `<code>${esc(i)}</code>`).join(", ")}</p>
      ${sub.negativeTriggers.length > 0 ? `<p class="negative-triggers"><strong>Negative triggers:</strong> ${sub.negativeTriggers.map((t) => `<em>${esc(t)}</em>`).join(" · ")}</p>` : ""}
    </div>`;
  }

  html += `<p><strong>Orchestrator:</strong></p>
    <div class="skill-card orchestrator-card">
      <h3>${esc(plan.orchestrator.name)}</h3>
      <p>${esc(plan.orchestrator.description)}</p>
      ${plan.orchestrator.negativeTriggers.length > 0 ? `<p class="negative-triggers"><strong>Negative triggers:</strong> ${plan.orchestrator.negativeTriggers.map((t) => `<em>${esc(t)}</em>`).join(" · ")}</p>` : ""}
    </div>
  </div>`;

  return html;
}

// ── Scan renderer ───────────────────────────────────────────────

function renderScanBody(data: ScanData): string {
  const scoreColor =
    data.healthScore >= 80
      ? SEVERITY_COLORS.LOW
      : data.healthScore >= 50
        ? SEVERITY_COLORS.HIGH
        : SEVERITY_COLORS.CRITICAL;

  const criticalHigh = data.overlapPairs.filter(
    (p: ScanPairEntry) => p.severity === "CRITICAL" || p.severity === "HIGH"
  );
  const medium = data.overlapPairs.filter((p: ScanPairEntry) => p.severity === "MEDIUM");

  let html = `
<div class="summary-cards">
  <div class="card card-stat">
    <div class="card-label">Health Score</div>
    <div class="card-value" style="color:${scoreColor}">${data.healthScore}/100</div>
  </div>
  <div class="card card-stat">
    <div class="card-label">Total Skills</div>
    <div class="card-value">${data.totalSkills}</div>
  </div>
  <div class="card card-stat">
    <div class="card-label">Conflicting Pairs</div>
    <div class="card-value" style="color:${criticalHigh.length > 0 ? SEVERITY_COLORS.CRITICAL : SEVERITY_COLORS.LOW}">${criticalHigh.length}</div>
  </div>
  <div class="card card-stat">
    <div class="card-label">Overloaded Skills</div>
    <div class="card-value" style="color:${data.overloadFindings.length > 0 ? SEVERITY_COLORS.HIGH : SEVERITY_COLORS.LOW}">${data.overloadFindings.length}</div>
  </div>
  <div class="card card-stat">
    <div class="card-label">Duplicate Skills</div>
    <div class="card-value" style="color:${data.duplicateFindings.length > 0 ? SEVERITY_COLORS.CRITICAL : SEVERITY_COLORS.LOW}">${data.duplicateFindings.length}</div>
  </div>
</div>`;

  if (criticalHigh.length > 0) {
    html += `<section>
  <h2 style="color:${SEVERITY_COLORS.CRITICAL}">Conflicting Pairs <span class="count">(${criticalHigh.length})</span></h2>
  <table>
    <thead><tr><th>Skill Pair</th><th>Overlap</th><th>Severity</th><th>Reason</th></tr></thead>
    <tbody>`;
    for (const pair of criticalHigh) {
      html += `<tr>
      <td><strong>${esc(pair.skillA)}</strong> ↔ <strong>${esc(pair.skillB)}</strong></td>
      <td>${(pair.overlapScore * 100).toFixed(0)}%</td>
      <td>${severityBadge(pair.severity)}</td>
      <td>${esc(pair.reason)}</td>
    </tr>`;
    }
    html += `</tbody></table></section>`;
  }

  if (medium.length > 0) {
    html += `<section>
  <h2 style="color:${SEVERITY_COLORS.MEDIUM}">Medium Overlap <span class="count">(${medium.length})</span></h2>
  <table>
    <thead><tr><th>Skill Pair</th><th>Overlap</th><th>Reason</th></tr></thead>
    <tbody>`;
    for (const pair of medium) {
      html += `<tr>
      <td>${esc(pair.skillA)} ↔ ${esc(pair.skillB)}</td>
      <td>${(pair.overlapScore * 100).toFixed(0)}%</td>
      <td>${esc(pair.reason)}</td>
    </tr>`;
    }
    html += `</tbody></table></section>`;
  }

  if (data.overloadFindings.length > 0) {
    html += `<section>
  <h2 style="color:${SEVERITY_COLORS.HIGH}">Scope Overload <span class="count">(${data.overloadFindings.length} skill${data.overloadFindings.length !== 1 ? "s" : ""})</span></h2>
  <p class="section-desc">These skills have descriptions that cover too many intents, which may cause routing confusion.</p>
  <table>
    <thead><tr><th>Skill</th><th>Length</th><th>Reason</th></tr></thead>
    <tbody>`;
    for (const finding of data.overloadFindings) {
      html += `<tr>
      <td><strong>${esc(finding.skillName)}</strong></td>
      <td>${finding.descriptionLength} chars</td>
      <td>${esc(finding.reason)}</td>
    </tr>`;
    }
    html += `</tbody></table></section>`;
  }

  if (data.duplicateFindings.length > 0) {
    html += `<section>
  <h2 style="color:${SEVERITY_COLORS.CRITICAL}">Duplicate Skills <span class="count">(${data.duplicateFindings.length})</span></h2>
  <p class="section-desc">Multiple SKILL.md files resolve to the same name. Only the first occurrence is used — duplicates are skipped.</p>
  <table>
    <thead><tr><th>Skill Name</th><th>Kept</th><th>Skipped</th></tr></thead>
    <tbody>`;
    for (const dup of data.duplicateFindings) {
      html += `<tr>
      <td><strong>${esc(dup.name)}</strong></td>
      <td>${esc(dup.keptPath)}</td>
      <td>${esc(dup.skippedPath)}</td>
    </tr>`;
    }
    html += `</tbody></table></section>`;
  }

  // Next steps callout
  const hasIssues =
    criticalHigh.length > 0 ||
    data.overloadFindings.length > 0 ||
    data.duplicateFindings.length > 0;
  if (hasIssues) {
    html += `<section class="callout">
  <h2>Next Steps</h2>
  <ul>`;
    if (criticalHigh.length > 0) {
      html += `<li>Run <code>homingo audit</code> to measure actual routing accuracy for conflicting pairs</li>`;
    }
    if (data.overloadFindings.length > 0) {
      html += `<li>Run <code>homingo lint --fix</code> to get rewrite suggestions and shard plans for overloaded skills</li>`;
    }
    if (data.duplicateFindings.length > 0) {
      html += `<li>Rename or remove duplicate skills to avoid routing ambiguity</li>`;
    }
    html += `</ul></section>`;
  } else {
    html += `<section class="callout callout-success">
  <h2>Fleet Looks Healthy</h2>
  <p>No critical overlaps or overloaded skills detected. Run <code>homingo audit</code> for a full routing accuracy test.</p>
</section>`;
  }

  return html;
}

// ── Utilities ──────────────────────────────────────────────────

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// ── CSS ────────────────────────────────────────────────────────

const CSS = `
:root {
  --bg: #f8fafc;
  --card-bg: #ffffff;
  --text: #1e293b;
  --text-muted: #64748b;
  --border: #e2e8f0;
  --critical: #dc2626;
  --high: #f59e0b;
  --medium: #3b82f6;
  --low: #22c55e;
  --accent: #6366f1;
}

* { margin: 0; padding: 0; box-sizing: border-box; }

body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
  padding: 2rem;
  max-width: 1200px;
  margin: 0 auto;
}

header {
  margin-bottom: 2rem;
  padding-bottom: 1rem;
  border-bottom: 2px solid var(--border);
}

header h1 {
  font-size: 1.5rem;
  margin-bottom: 0;
}

.header-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 0.75rem;
}

.home-link {
  color: var(--accent);
  text-decoration: none;
  font-size: 0.9rem;
  font-weight: 500;
  padding: 0.4rem 0.75rem;
  border: 1px solid var(--accent);
  border-radius: 6px;
  transition: background 0.15s, color 0.15s;
}

.home-link:hover {
  background: var(--accent);
  color: #fff;
}

.meta-bar {
  display: flex;
  flex-wrap: wrap;
  gap: 1rem;
  font-size: 0.85rem;
  color: var(--text-muted);
}

.meta-item code {
  font-family: "SF Mono", "Fira Code", monospace;
  background: var(--border);
  padding: 1px 4px;
  border-radius: 3px;
  font-size: 0.8rem;
}

.summary-cards {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  gap: 1rem;
  margin-bottom: 2rem;
}

.card {
  background: var(--card-bg);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1rem 1.25rem;
}

.card-stat .card-label {
  font-size: 0.8rem;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.card-stat .card-value {
  font-size: 1.75rem;
  font-weight: 700;
  margin-top: 0.25rem;
}

.card-pass { border-left: 4px solid var(--low); }
.card-fail { border-left: 4px solid var(--critical); }

section {
  margin-bottom: 2rem;
}

section h2 {
  font-size: 1.25rem;
  margin-bottom: 0.75rem;
}

.count {
  font-weight: 400;
  font-size: 0.9rem;
  color: var(--text-muted);
}

table {
  width: 100%;
  border-collapse: collapse;
  background: var(--card-bg);
  border-radius: 8px;
  overflow: hidden;
  border: 1px solid var(--border);
}

thead th {
  text-align: left;
  padding: 0.75rem 1rem;
  background: #f1f5f9;
  font-size: 0.8rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--text-muted);
}

tbody td {
  padding: 0.75rem 1rem;
  border-top: 1px solid var(--border);
  font-size: 0.9rem;
}

details {
  margin: 0.5rem 0;
}

summary {
  cursor: pointer;
  font-size: 0.85rem;
  color: var(--accent);
  font-weight: 500;
}

.misroute-list {
  list-style: none;
  padding: 0.5rem 0;
}

.misroute-list li {
  padding: 0.5rem 0;
  border-bottom: 1px solid var(--border);
  font-size: 0.85rem;
}

.misroute-list li:last-child { border-bottom: none; }

.prompt-text {
  font-style: italic;
  color: var(--text-muted);
}

.misroute-detail {
  font-size: 0.8rem;
}

.more {
  color: var(--text-muted);
  font-style: italic;
}

.rewrite-card {
  background: var(--card-bg);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1.25rem;
  margin-bottom: 1rem;
}

.rewrite-card h3 { margin-bottom: 0.5rem; }
.rewrite-card .reasoning { color: var(--text-muted); font-size: 0.9rem; margin-bottom: 0.75rem; }

.diff-view {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1rem;
  margin-bottom: 0.75rem;
}

.diff-old, .diff-new {
  border-radius: 6px;
  padding: 0.75rem;
  font-size: 0.85rem;
}

.diff-old {
  background: #fef2f2;
  border: 1px solid #fecaca;
}

.diff-new {
  background: #f0fdf4;
  border: 1px solid #bbf7d0;
}

.diff-old pre, .diff-new pre {
  white-space: pre-wrap;
  word-break: break-word;
  font-family: "SF Mono", "Fira Code", monospace;
  font-size: 0.8rem;
  margin-top: 0.5rem;
}

.conflicts-with { font-size: 0.85rem; color: var(--text-muted); }
.conflicts-with code { background: var(--border); padding: 1px 4px; border-radius: 3px; }

.skill-card {
  background: var(--card-bg);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1.25rem;
  margin-bottom: 1rem;
}

.skill-card h3 { margin-bottom: 0.5rem; }
.skill-card code { background: var(--border); padding: 1px 4px; border-radius: 3px; font-size: 0.8rem; }

.orchestrator-card {
  border-left: 4px solid var(--accent);
}

.negative-triggers {
  font-size: 0.85rem;
  color: var(--text-muted);
  margin-top: 0.5rem;
}

.negative-triggers em {
  background: #fef3c7;
  padding: 1px 4px;
  border-radius: 3px;
  font-style: normal;
  font-size: 0.8rem;
}

.section-desc {
  color: var(--text-muted);
  font-size: 0.9rem;
  margin-bottom: 1rem;
}

.shard-details {
  margin-top: 1rem;
  padding-top: 0.75rem;
  border-top: 1px solid var(--border);
}

footer {
  margin-top: 3rem;
  padding-top: 1rem;
  border-top: 1px solid var(--border);
  text-align: center;
  font-size: 0.8rem;
  color: var(--text-muted);
}

footer code {
  font-family: "SF Mono", "Fira Code", monospace;
  background: var(--border);
  padding: 1px 4px;
  border-radius: 3px;
}

ol, ul { padding-left: 1.5rem; }
li { margin-bottom: 0.25rem; }

.callout {
  background: #fefce8;
  border: 1px solid #fde68a;
  border-radius: 8px;
  padding: 1.25rem;
}

.callout h2 { font-size: 1.1rem; margin-bottom: 0.5rem; }
.callout code {
  font-family: "SF Mono", "Fira Code", monospace;
  background: #fef3c7;
  padding: 1px 4px;
  border-radius: 3px;
  font-size: 0.85rem;
}

.callout-success {
  background: #f0fdf4;
  border-color: #bbf7d0;
}

.callout-success code {
  background: #dcfce7;
}

.skill-inventory {
  margin-bottom: 2rem;
  background: var(--card-bg);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 0.75rem 1rem;
}

.skill-inventory summary {
  cursor: pointer;
  font-size: 0.9rem;
  font-weight: 500;
  color: var(--text-muted);
}

.skill-inventory table { margin-top: 0.75rem; }

.skill-desc {
  font-size: 0.85rem;
  color: var(--text-muted);
  max-width: 600px;
}

@media (max-width: 768px) {
  body { padding: 1rem; }
  .summary-cards { grid-template-columns: 1fr 1fr; }
  .diff-view { grid-template-columns: 1fr; }
  .meta-bar { flex-direction: column; gap: 0.5rem; }
}
`;
