import type { CommandName, RunMetadata } from "./run-metadata.js";

export interface LogEntry {
  metadata: RunMetadata;
  htmlPath: string;
}

export type LogsByCommand = Record<CommandName, LogEntry[]>;

/**
 * Generate a self-contained HTML page that lets the user browse
 * the last 10 runs per command with tabs and "View Report" links.
 */
export function generateLogsViewer(allRuns: LogsByCommand): string {
  const commands: CommandName[] = ["audit", "lint", "scan"];
  const runData = JSON.stringify(allRuns);

  const tabs = commands
    .map(
      (cmd) =>
        `<button class="tab-btn" data-tab="${cmd}" onclick="switchTab('${cmd}')">${capitalize(cmd)} <span class="badge">${allRuns[cmd]?.length ?? 0}</span></button>`
    )
    .join("\n    ");

  const panels = commands
    .map((cmd) => {
      const runs = allRuns[cmd] || [];
      if (runs.length === 0) {
        return `<div class="tab-panel" id="panel-${cmd}"><p class="empty">No ${cmd} runs recorded yet.</p></div>`;
      }

      let rows = "";
      for (const entry of runs) {
        const m = entry.metadata;
        const date = m.timestamp.slice(0, 19).replace("T", " ");
        const duration = (m.durationMs / 1000).toFixed(1);
        const totalTokens = m.tokens.total.toLocaleString();
        const summary = getResultSummary(m);

        rows += `<tr>
          <td>${esc(date)}</td>
          <td>${duration}s</td>
          <td>${esc(m.model)}</td>
          <td>${m.skillCount}</td>
          <td>${totalTokens}</td>
          <td>${esc(summary)}</td>
          <td><a href="file://${esc(entry.htmlPath)}" class="view-link">View Report</a></td>
        </tr>`;
      }

      return `<div class="tab-panel" id="panel-${cmd}">
        <table>
          <thead>
            <tr><th>Date</th><th>Duration</th><th>Model</th><th>Skills</th><th>Tokens</th><th>Result</th><th></th></tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>
      </div>`;
    })
    .join("\n  ");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Homingo — Run History</title>
<style>${VIEWER_CSS}</style>
</head>
<body>
<header>
  <h1>🐦 Homingo Run History</h1>
</header>
<nav class="tab-bar">
  ${tabs}
</nav>
<main>
  ${panels}
</main>
<footer>
  <p>Generated by <strong>Homingo</strong></p>
</footer>
<script>
const runData = ${runData};
function switchTab(cmd) {
  document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
  document.querySelectorAll('.tab-panel').forEach(p => p.style.display = 'none');
  document.querySelector('[data-tab="' + cmd + '"]').classList.add('active');
  document.getElementById('panel-' + cmd).style.display = 'block';
}
// Activate first tab with runs, or first tab
const first = ${JSON.stringify(commands)}.find(c => runData[c] && runData[c].length > 0) || 'audit';
switchTab(first);
</script>
</body>
</html>`;
}

function getResultSummary(m: RunMetadata): string {
  const r = m.result;
  switch (r.type) {
    case "audit":
      return `${r.fleetErrorRate}% error rate, ${r.criticalCount} critical`;
    case "lint":
      return `${r.passingCount} pass, ${r.failingCount} fail, ${r.overloadedSkills} overloaded`;
    case "scan":
      return `health ${r.healthScore}/100, ${r.conflictingPairs} conflicts, ${r.overloadedSkills} overloaded, ${r.duplicateSkills} duplicates`;
  }
}

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

const VIEWER_CSS = `
:root {
  --bg: #f8fafc;
  --card-bg: #ffffff;
  --text: #1e293b;
  --text-muted: #64748b;
  --border: #e2e8f0;
  --accent: #6366f1;
}

* { margin: 0; padding: 0; box-sizing: border-box; }

body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
  padding: 2rem;
  max-width: 1200px;
  margin: 0 auto;
}

header h1 { font-size: 1.5rem; margin-bottom: 1rem; }

.tab-bar {
  display: flex;
  gap: 0.5rem;
  margin-bottom: 1.5rem;
  border-bottom: 2px solid var(--border);
  padding-bottom: 0;
}

.tab-btn {
  background: none;
  border: none;
  padding: 0.5rem 1rem;
  font-size: 0.9rem;
  cursor: pointer;
  color: var(--text-muted);
  border-bottom: 2px solid transparent;
  margin-bottom: -2px;
  transition: color 0.15s, border-color 0.15s;
}

.tab-btn:hover { color: var(--text); }
.tab-btn.active {
  color: var(--accent);
  border-bottom-color: var(--accent);
  font-weight: 600;
}

.badge {
  display: inline-block;
  background: var(--border);
  color: var(--text-muted);
  font-size: 0.7rem;
  padding: 1px 6px;
  border-radius: 10px;
  margin-left: 4px;
}

.tab-btn.active .badge {
  background: var(--accent);
  color: #fff;
}

.tab-panel { display: none; }

.empty {
  text-align: center;
  color: var(--text-muted);
  padding: 3rem 0;
  font-size: 0.95rem;
}

table {
  width: 100%;
  border-collapse: collapse;
  background: var(--card-bg);
  border-radius: 8px;
  overflow: hidden;
  border: 1px solid var(--border);
}

thead th {
  text-align: left;
  padding: 0.75rem 1rem;
  background: #f1f5f9;
  font-size: 0.8rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--text-muted);
}

tbody td {
  padding: 0.75rem 1rem;
  border-top: 1px solid var(--border);
  font-size: 0.9rem;
}

.view-link {
  color: var(--accent);
  text-decoration: none;
  font-weight: 500;
}

.view-link:hover { text-decoration: underline; }

footer {
  margin-top: 3rem;
  padding-top: 1rem;
  border-top: 1px solid var(--border);
  text-align: center;
  font-size: 0.8rem;
  color: var(--text-muted);
}

@media (max-width: 768px) {
  body { padding: 1rem; }
  .tab-bar { flex-wrap: wrap; }
}
`;
